### ISSUE TITLE
Grafana 10 Navigation Panel customization for Apps

### ISSUE THREAD

**Issue by centenico** [VolkovLabs/volkovlabs.io#472]
Hi @mikhail-vl , sorry for the "wrong" use of Github's issues but I wanted to give back to your awesome project and tell you about something I just discovered.
In Grafana 10, they have re-organized and grouped some of the menus, like the Apps plugins under the "Apps" nav item.
Previously they showed in the root nav with a customized icon, which was (in my opinion) better, but you can still do it :

Basically you'll just have to edit the grafana.ini settings specifying in the navigation.app_sections the id of your app and the id of the menu (in my case, root, which is as before in the main navigation-menu), and optionally the weight.

```
[navigation.app_sections]
myorg-basic-app = root
myorg-dashboard-app = root -9999
```

You can find the ""documentation"" in this discussion right here.
https://github.com/grafana/grafana/discussions/58910#discussioncomment-5864203

Hope that'll help you with some of your customizations.
Thanks again for your awesome work and enormous amount of useful help and informations.

**Comment by mikhail-vl** [comment]
@centenico Thank you for letting us know. I was looking for it.
  The official answer from the Grafana team was it was impossible to do. Looks like it's not anymore.
  If you can edit it in the `grafana.ini` it should be possible to do with environment variables like
  
```
GF_NAVIGATION_APP_SECTIONS_myorg-basic-app=root
```

  I will try and include it in the customization documentation.

**Comment by centenico** [comment]
Glad to have been helpful!
Have a good day.

**Comment by mikhail-vl** [comment]
@centenico Thank you!

  The environment variable did not work. I updated configuration directly in the Dockerfile:

```
RUN sed -i 's|\[navigation.app_sections\]|\[navigation.app_sections\]\nvolkovlabs-app=root|g' /usr/share/grafana/conf/defaults.ini
```
