### ISSUE TITLE
Ability to hide 'json' code when viewer clicks 'inspect'

### ISSUE THREAD

**Issue by jboyd170** [VolkovLabs/volkovlabs.io#552]
Thanks for the help on customizing Grafana -- i'm trying to figure out how to keep users with 'view' authority from viewing the dashboard json, which can be viewed using panel > inspect.  Thanks for the good info!

**Comment by mikhail-vl** [comment]
@jboyd170 Glad it helped! You can remove the JSON tab from Inspect, but users can still see the returned dashboard JSON in the Network requests.

  There is no way to hide dashboard JSON in the Grafana frontend architecture. It requires server-side rendering.
